language: csharp
mono: none
dotnet: 3.1
solution: src/MaybeSharp.sln
script:
  - dotnet restore src/MaybeSharp.sln
  - dotnet build src/MaybeSharp.sln -f netcoreapp3.1
  - dotnet test src/MaybeSharp.sln -f netcoreapp3.1
  - dotnet test src/MaybeSharp.sln -f netcoreapp3.1 /p:CollectCoverage=true /p:Include="[MaybeSharp]*"
