language: csharp
mono: none
dotnet: 2.1.500
solution: src/MaybeSharp.sln
script:
  - dotnet restore src/MaybeSharp.sln
  - dotnet build src/MaybeSharp.sln
  - dotnet test src/MaybeSharp.sln
  - dotnet test src/MaybeSharp.sln /p:CollectCoverage=true /p:Include="[MaybeSharp]*"
