name: .NET 5 CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test (with Coverage)
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: dotnet build src/MaybeSharp.sln
      - run: dotnet test src/MaybeSharp.sln -f net5 /p:CollectCoverage=true /p:Include="[MaybeSharp]*"
